import type { Metadata } from "next";
import './globals.css'

export const metadata: Metadata = {
  title: "Indian Dowry Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head />
      <body>{children}</body>
    </html>
  )
}
